os: osx
osx_image: xcode10.2
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script:
  - xcodebuild clean -project Animoji.xcodeproj -scheme Animoji -destination "platform=iOS Simulator,name=iPhone X,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
  - xcodebuild clean -project Animoji.xcodeproj -scheme Example -destination "platform=iOS Simulator,name=iPhone X,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
