//
//  AVTAvatarInstance.h
//  Animoji
//
//  Created by Lasha Efremidze on 11/10/17.
//  Copyright © 2017 Lasha Efremidze. All rights reserved.
//

/* Generated by RuntimeBrowser
 Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

//@interface AVTAvatarInstance : NSObject <SCNSceneRendererDelegate> {
//    bool  _animated;
//    SCNNode * _assetContainer;
//    AVTAvatar * _avatar;
//    SCNNode * _avatarNode;
//    NSMutableArray * _clipsPlaying;
//    unsigned int  _componentDirtyMask;
//    AVTComponentInstance * _componentInstances;
//    NSMutableArray * _correctivedMorpherDescriptors;
//    NSMutableDictionary * _faceMorphVariants;
//    SCNNode * _headNode;
//    bool  _ignoreRigsDidChange;
//    SCNNode * _leftEye;
//    struct SCNVector3 { 
//        float x; 
//        float y; 
//        float z; 
//    }  _lookAt;
//    NSMutableArray * _physicalizedMorpherDescriptors;
//    AVTPhysicsController * _physicsController;
//    AVTPupilDirectionDescriptor * _pupilDirectionDescriptor;
//    long long  _quality;
//    SCNNode * _referenceNode;
//    SCNNode * _rightEye;
//    SCNNode * _skeleton;
//    AVTAvatarSkeletonInstance * _skeletonInstance;
//    NSDictionary * specializationSettings;
//}
//
//@property (getter=isAnimated, nonatomic) bool animated;
//@property (readonly) SCNNode *avatarNode;
//@property (readonly, copy) NSString *debugDescription;
//@property (readonly, copy) NSString *description;
//@property (readonly) unsigned long long hash;
//@property (readonly) SCNNode *headNode;
//@property (nonatomic) long long quality;
//@property (readonly) AVTAvatarSkeletonInstance *skeletonInstance;
//@property (nonatomic, retain) NSDictionary *specializationSettings;
//@property (readonly) Class superclass;
//
//+ (id)animationClipForExpression:(long long)arg1;
//+ (id)animationClips;
//+ (id)avatarInstanceWithAvatar:(id)arg1;
//
//- (void).cxx_destruct;
//- (void)_cacheFaceMorphVariants:(id)arg1;
//- (struct SCNVector3 { float x1; float x2; float x3; })absolutePositionForRigElevation:(double)arg1 spacing:(double)arg2 symmetry:(bool)arg3;
//- (void)applyCorrectiveBlendShape;
//- (void)autoUpdateComponents;
//- (void)avatarComponentDidChange:(id)arg1;
//- (void)avatarComponentDidUpdate:(id)arg1;
//- (void)avatarComponentSyncUpdate:(id)arg1;
//- (void)avatarEyeColorDidUpdate:(id)arg1;
//- (void)avatarMorphVariantDidChange:(id)arg1;
//- (id)avatarNode;
//- (void)avatarRigsDidChange:(id)arg1;
//- (void)avatarSkinDidUpdate:(id)arg1;
//- (id)bonesForRig:(id)arg1;
//- (void)commonInit;
//- (id)componentInstanceWithType:(long long)arg1;
//- (id)computeSkinImage;
//- (struct SCNVector3 { float x1; float x2; float x3; })currentLookAt;
//- (void)didAddToScene:(id)arg1;
//- (void)driveBlendShapeWithPhysics;
//- (void)getRigValues:(id)arg1 symmetry:(bool)arg2 withBone:(id)arg3 spacingOut:(double*)arg4 elevationOut:(double*)arg5 scaleOut:(double*)arg6 rotationOut:(double*)arg7;
//- (id)headNode;
//- (id)init;
//- (id)initWithAvatar:(id)arg1;
//- (bool)isAnimated;
//- (void)lookAt:(struct SCNVector3 { float x1; float x2; float x3; })arg1;
//- (void)lookAt:(struct SCNVector3 { float x1; float x2; float x3; })arg1 withDuration:(double)arg2;
//- (id)playAnimationClip:(id)arg1;
//- (id)playAnimationClip:(id)arg1 usingSceneTime:(bool)arg2;
//- (id)playAnimationClip:(id)arg1 usingSceneTime:(bool)arg2 withCompletion:(id)arg3;
//- (id)playAnimationClip:(id)arg1 withCompletion:(id)arg2;
//- (id)playAnimationClipForSnapshotting:(id)arg1;
//- (long long)quality;
//- (void)renderer:(id)arg1 didApplyAnimationsAtTime:(double)arg2;
//- (void)rotateHead:(double)arg1;
//- (void)setAnimated:(bool)arg1;
//- (void)setAvatarNode:(id)arg1;
//- (void)setQuality:(long long)arg1;
//- (void)setSpecializationSettings:(id)arg1;
//- (id)skeletonInstance;
//- (double)skinTextureSize;
//- (id)specializationSettings;
//- (void)stopAndRemoveAnimationClips;
//- (void)update;
//- (void)updateAnimations;
//- (void)updateBoneForRig:(id)arg1;
//- (void)updateBonesFromRigs;
//- (void)updateHairMorphVariant;
//- (void)updateHeadMorphVariant;
//- (void)updateHeadMorphVariantWithType:(long long)arg1 variant:(id)arg2;
//- (void)updateModularCompositionOfComponent:(id)arg1 withNode:(id)arg2;
//- (void)updatePupilReflectionDirection;
//- (void)updateRig:(id)arg1 fromBone:(id)arg2 symmetry:(bool)arg3 applyRange:(bool)arg4;
//- (void)updateSkin:(id)arg1;
//- (void)updateSkinMaterial:(id)arg1;
//- (void)willRemoveFromScene:(id)arg1;
//
//@end

@import Foundation;

@interface AVTAvatarInstance : NSObject
@end
