//
//  AVTAvatarView.h
//  Animoji
//
//  Created by Lasha Efremidze on 11/10/17.
//  Copyright © 2017 Lasha Efremidze. All rights reserved.
//

/* Generated by RuntimeBrowser
 Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

//@interface AVTAvatarView : SCNView {
//    AVTAvatarInstance * _avatarInstance;
//    SCNNode * _avatarNode;
//    unsigned long long  _currentExpressionIndex;
//    long long  _framingMode;
//    <SCNSceneRendererDelegate> * _fwdDelegate;
//    bool  _lockLookAt;
//    SCNNode * cameraNode;
//    struct SCNVector3 {
//        float x;
//        float y;
//        float z;
//    }  eyeLeftPos;
//    struct SCNVector3 {
//        float x;
//        float y;
//        float z;
//    }  eyeRightPos;
//}
//
//@property (nonatomic, retain) AVTAvatarInstance *avatarInstance;
//@property (nonatomic) long long framingMode;
//
//+ (id)defaultEnvironment;
//
//- (void).cxx_destruct;
//- (void)_avtCommonInit;
//- (id)avatarInstance;
//- (void)avatarInstanceDidChange;
//- (id)delegate;
//- (long long)framingMode;
//- (id)initWithCoder:(id)arg1;
//- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 options:(id)arg2;
//- (void)renderer:(id)arg1 didApplyAnimationsAtTime:(double)arg2;
//- (void)renderer:(id)arg1 didApplyConstraintsAtTime:(double)arg2;
//- (void)renderer:(id)arg1 didRenderScene:(id)arg2 atTime:(double)arg3;
//- (void)renderer:(id)arg1 didSimulatePhysicsAtTime:(double)arg2;
//- (void)renderer:(id)arg1 updateAtTime:(double)arg2;
//- (void)renderer:(id)arg1 willRenderScene:(id)arg2 atTime:(double)arg3;
//- (void)setAvatarInstance:(id)arg1;
//- (void)setDelegate:(id)arg1;
//- (void)setFramingMode:(long long)arg1;
//- (void)setup;
//
//@end

@import SceneKit;

@class AVTAvatarInstance;

@interface AVTAvatarView : SCNView
@property (nonatomic, retain) AVTAvatarInstance *avatarInstance;
@end
