//
//  AVTAvatarView.h
//  Animoji
//
//  Created by Lasha Efremidze on 11/10/17.
//  Copyright © 2017 Lasha Efremidze. All rights reserved.
//

/* Generated by RuntimeBrowser
 Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@import SceneKit;

@class AVTAvatarInstance;

@interface AVTAvatarView : SCNView
@property (nonatomic, retain) AVTAvatarInstance *avatarInstance;
@end
