//
//  AVTAnimoji.h
//  Animoji
//
//  Created by Lasha Efremidze on 3/15/20.
//  Copyright © 2020 Lasha Efremidze. All rights reserved.
//

/* Generated by RuntimeBrowser
 Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@import Foundation;
#import "AVTAvatar.h"

@interface AVTAnimoji: AVTAvatar
+ (id)animojiNamed:(id)arg1;
+ (id)animojiNames;
+ (UIImage *)thumbnailForAnimojiNamed:(id)arg1 options:(id)arg2;
@end
