//
//  AVTView.h
//  Animoji
//
//  Created by Lasha Efremidze on 3/15/20.
//  Copyright © 2020 Lasha Efremidze. All rights reserved.
//

/* Generated by RuntimeBrowser
 Image: /System/Library/PrivateFrameworks/AvatarUI.framework/AvatarUI
 */

@import UIKit;

@class AVTMultiAvatarController;
@protocol AVTPresenterDelegate;

@interface AVTCarouselController : UIViewController
@property (nonatomic, retain) UIView *avtViewContainer;
@property (nonatomic, retain) AVTMultiAvatarController *multiAvatarController
//@property (nonatomic) __weak id <AVTPresenterDelegate> presenterDelegate;
//@property(readonly, nonatomic) UIView *view;
+ (id)recordingCarouselForRecordDataSource:(id)arg1;
+ (id)displayingCarouselForRecordDataSource:(id)arg1;
@end
