//
//  AVTPuppet.h
//  Animoji
//
//  Created by Lasha Efremidze on 11/10/17.
//  Copyright © 2017 Lasha Efremidze. All rights reserved.
//

/* Generated by RuntimeBrowser
 Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@import Foundation;

@class AVTAvatarInstance;

@interface AVTPuppet: NSObject
+ (id)puppetNamed:(id)arg1 options:(id)arg2;
+ (id)puppetNames;
+ (UIImage *)thumbnailForPuppetNamed:(id)arg1 options:(id)arg2;
@end
