//
//  AVTView.h
//  Animoji
//
//  Created by Lasha Efremidze on 3/15/20.
//  Copyright © 2020 Lasha Efremidze. All rights reserved.
//

/* Generated by RuntimeBrowser
 Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@import SceneKit;
#import "AVTAnimoji.h"

@interface AVTView : SCNView
@property (nonatomic, retain) AVTAvatar *avatar;
@end
